before:
  hooks:
  - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
dockers:
- use: buildx
  goos: linux
  goarch: amd64
  image_templates:
  - "ghcr.io/z5labs/{{ .ProjectName }}:{{.Tag }}-amd64"
  - "ghcr.io/z5labs/{{ .ProjectName }}:v{{.Major }}-amd64"
  - "ghcr.io/z5labs/{{ .ProjectName }}:v{{.Major }}.{{ .Minor }}-amd64"
  - "ghcr.io/z5labs/{{ .ProjectName }}:latest-amd64"
  build_flag_templates:
  - "--platform=linux/amd64"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
- use: buildx
  goos: linux
  goarch: arm64
  image_templates:
  - "ghcr.io/z5labs/{{ .ProjectName }}:{{.Tag }}-arm64v8"
  - "ghcr.io/z5labs/{{ .ProjectName }}:v{{.Major }}-arm64v8"
  - "ghcr.io/z5labs/{{ .ProjectName }}:v{{.Major }}.{{ .Minor }}-arm64v8"
  - "ghcr.io/z5labs/{{ .ProjectName }}:latest-arm64v8"
  build_flag_templates:
  - "--platform=linux/arm64/v8"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
- name_template: ghcr.io/z5labs/{{ .ProjectName }}:v{{ .Version }}
  image_templates:
  - ghcr.io/z5labs/{{ .ProjectName }}:v{{ .Version }}-amd64
  - ghcr.io/z5labs/{{ .ProjectName }}:v{{ .Version }}-arm64v8
- name_template: ghcr.io/z5labs/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/z5labs/{{ .ProjectName }}:latest-amd64
  - ghcr.io/z5labs/{{ .ProjectName }}:latest-arm64v8
archives:
- name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  wrap_in_directory: true
  format_overrides:
  - goos: windows
    format: zip
  replacements:
    darwin: macos
    linux: linux
    windows: windows
    386: i386
    amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
snapshot:
  name_template: "snapshot_{{ .Commit }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs'
    - '^test'
    - '^build'
release:
  name_template: "{{ .ProjectName }} v{{ .Version }}"
